# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-win-linux:
    name: release linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3
    - name: Install cross build gcc
      run: sudo apt-get -y install gcc-aarch64-linux-gnu
    - name: Build and release binary
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_command: export CGO_ENABLED=1
        overwrite: true
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: mailfetcher
        asset_name: "mailfetcher-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        extra_files: configs/EXAMPLE.txt
