# .github/workflows/release.yaml

on:
  #push:
  #  branches: [master]
  release:
    types: [created]

jobs:
  release-win:
    name: release windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - run: ls -l /usr/local/bin
    - run: ls -l /usr/bin
    - run: /usr/local/bin/cc --version
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_command: apt-get install gcc-mingw-w64; export CGO_ENABLED=1;export CC=x86_64-w64-mingw32-gcc
        overwrite: true
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: mailfetcher
        asset_name: "mailfetcher-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        extra_files: configs/EXAMPLE.txt
